markdown: kramdown
highlighter: rouge
pygments: true

# Site name (head)
name: ActivityPub Documentation

# Site description (head)
description: A PHP implementation of ActivityPub protocol based upon the ActivityStreams 2.0 data format.

# Github repositories and download URLs
github_repository_url: https://github.com/landrok/activitypub
github_doc_repository_url: https://github.com/landrok/activitypub/tree/master/docs
github_author_url: https://github.com/landrok

github_author_name: landrok

